working_dir: "test_feat_extractor"
image_labels: "label_table.csv"
train_val_split:
  - 0.8
  - 0.2
query_train_path: "query/train" 
ref_train_path: "reference_v1"
query_test_path: "query/test"
ref_test_path: "ref"

model_hyperparameters:
  option_0:
    end_layer: 7
    embedding_dim: 500
    model_name: "resnet50"

training_hyperparameters:
  option_0:
    batch_size: 128
    epochs: 300
    early_stopping: 15
    margin: 5.0
    learning_rate: 0.0001
    optimizer: "Adam"
    step_size: 5
    gamma: 0.5
  option_1:
    batch_size: 16
    epochs: 300
    early_stopping: 15
    margin: 2.0
    learning_rate: 0.001
    optimizer: "Adam"
    step_size: 50
    gamma: 0.5
